### ISSUE TITLE
Using stac-validator as a library

### ISSUE THREAD

**Issue by matthewhanson** [sparkgeo/stac-validator#159]
It would be useful if stac-validator could be used as a validator in my own code. For instance I want to be able to validate dynamically generated STAC metadata, or validate on a sampling of items from each collection in a very large catalog.

Right now, the code assumes this the CLI is used so it's assuming a URL or local file with the metadata, and it prints the results to the screen.

I'd like to have the ability to pass in a dictionary rather than have to write it to a file. I'd also like the validation to return the status so I get a list of dictionaries that I can parse in order to automate large scale validation.

**Comment by jonhealy1** [comment]
@matthewhanson Ok great thanks. I will look at fixing that.

**Comment by jonhealy1** [comment]
@matthewhanson I moved the std out to the cli so that part should work fine. I pushed it to the validate_dict branch. If you can think of anything else, don't hesitate to let us know. Thanks!

**Comment by matthewhanson** [comment]
The validate_dict doesn't seem to work, but not sure where the problem lies.  It appears to validate, but is always returning True.

I created a simply collection, but without the type field. Using the stac-validator CLI is fails, but using validate_dict it passes.  
It seems to be using the `custom_val` function when using validate_dict, but `default_val` when using the CLI. I'm not sure I understand the differences here.

**Comment by jonhealy1** [comment]
Hi Matthew. Can you post the collection you are testing so I can try it out? When you use the CLI are you using any flags? I have tried testing validate_dict on a collection without the type field and I get this message: 

{'version': '1.0.0-rc.3', 'path': None, 'schema': ['https://schemas.stacspec.org/v1.0.0-rc.3/collection-spec/json-schema/collection.json'], 'valid_stac': False, 'error_type': 'ValidationError', 'error_message': "'type' is a required property of the root of the STAC object"}

**Comment by jbants** [comment]
Hey @matthewhanson, we added a `return True/False` to the function rather than the implicit `None`.
