### ISSUE TITLE
Reformat error messages for readability.

### ISSUE THREAD

**Issue by alanjleonard** [sparkgeo/stac-validator#17]
Put the error and the source on two different lines, as opposed to two columns. Make the error message larger than the source. 
If the source URL is too long, add an ellipsis in the middle to preserve the end of the path.
![error-reformat](https://user-images.githubusercontent.com/35936230/47240493-7974b380-d3b6-11e8-956f-b08db16962b0.png)

**Comment by brianbancroft** [comment]
Another styling problem that is similar is the styling. Right now, there boxes extend outside of the viewport, when their content should just wrap down. 

![image](https://user-images.githubusercontent.com/6225122/47301890-081f4580-d5ee-11e8-9005-12934c103a93.png)

I will be tackling both visual defects in this issue.

**Comment by brianbancroft** [comment]
All issues discussed in this ticket have been resolved for the develop branch of `staclint`. [[link](https://github.com/sparkgeo/staclint/commit/ac5f79a8fe244a8b13041467c95f5eede40d09e3)]


![image](https://user-images.githubusercontent.com/6225122/47369896-9ceb7700-d6b2-11e8-9acb-f592bbcb126e.png)
