### ISSUE TITLE
Wording of one particular error message may be vague. 

### ISSUE THREAD

**Issue by brianbancroft** [sparkgeo/stac-validator#34]
When testing `https://cbers-stac.s3.amazonaws.com/CBERS4/MUX/057/122/catalog.json`, the first error message that comes up is as follows:

`'stac_version' is a required property of []`

![image](https://user-images.githubusercontent.com/6225122/48306732-10dbab00-e50c-11e8-95b4-e0df7bbe36d5.png)

This might be a bit too vague, and may confuse some under-caffeinated, but otherwise-diligent individuals.

**Comment by m-mohr** [comment]
Does is get better if you add a `"const": "0.6.2"` to the stac_version field in the schema? I already wondered whether we should include this in the JSON schema anyway as for each released version there's exactly one value we except.
