### ISSUE TITLE
Reduce number of http calls 

### ISSUE THREAD

**Issue by vincentsarago** [sparkgeo/stac-validator#36]
As part of #35, I'd like to propose to remove this part 
https://github.com/sparkgeo/stac-validator/blob/2bc527cdf5b05bab499100e88254a3bdd3d65fe1/stac_validator.py#L50-L62

where we fetch the available STAC version. 

IMO, this is maybe unnecessary and we may be able to produce the same error message (if a wrong version is provided) by returning a useful error in https://github.com/sparkgeo/stac-validator/blob/2bc527cdf5b05bab499100e88254a3bdd3d65fe1/stac_validator.py#L81 
if the files don't exist 

cc @jbants

**Comment by jbants** [comment]
I'm cool with redoing this under the fetch_specs method. I'd still like to return what the valid STAC versions are to the user.
