### ISSUE TITLE
Possible changes to STAC schema at https://cdn.staclint.com exposes 3 Unit tests failures

### ISSUE THREAD

**Issue by hasselstromk** [sparkgeo/stac-validator#57]
<img width="1613" alt="Screen Shot 2020-03-02 at 7 54 31 AM" src="https://user-images.githubusercontent.com/6146512/75687568-389fd680-5c5b-11ea-8f37-fe672ae09764.png">

Running unit tests on master as of 3/2/2020, I see 3 test failures - output attached.  These tests are failing when try to pull a non-existent file at 'https://cdn.staclint.com/master/geojson.json'.  The last known version i can find this file is at https://cdn.staclint.com/v0.7.0/geojson.json. Not sure if tests are now wrong for > version 0.7 or if validation has fundamentally changed.

**Comment by jbants** [comment]
Hi @hasselstromk.
Ive updated the CDN to have a copy of the geojson spec under the master route now.

I haven't updated the validator in some time so it may not be correctly validating your STAC file.
